apiVersion: v1
kind: Pod
metadata:
  name: list-pods
  namespace: default
spec:
  serviceAccountName: ubuntu-sa
  containers:
  - name: list-pods
    image: bitnami/kubectl:latest
    #permite que o container fique em loop sempre disponível, caso contŕario, completed
    command: ["/bin/sh", "-c", "while true; do sleep 30; done"] 

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ubuntu-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ubuntu-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ubuntu-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ubuntu-role
subjects:
- kind: ServiceAccount
  name: ubuntu-sa
  namespace: default