apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: c25ka2Fuc0tKTktTbmRAQDQzNAo=
  POSTGRES_USER: YWRtaW4K
---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  labels:
    app: app-config
spec:
  containers:
  - name: config-cont
    image: postgres:15.0
    envFrom:
    - secretRef:
        name: db-secret

