apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /volume-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  labels:
    app: volume
spec:
  containers:
  - name: volume-cont
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "while true; do sleep 30; done"]
    volumeMounts:
    - mountPath: /volume-data
      name: volume-ex5
  volumes: 
    - name: volume-ex5
      persistentVolumeClaim:
        claimName: volume-pvc


